#ifndef OBFUSCATE_H
#define OBFUSCATE_H

struct Ingredient {
  char *name;
  char *measure;
  char c;
};

struct Ingredient ings[] = {
  {"all-purpose flour", "cup"},
  {"baking powder", "tablespoon"},
  {"baking soda", "teaspoon"},
  {"granulated sugar", "cup"},
  {"brown sugar", "cup"},
  {"powdered sugar", "cup"},
  {"salt", "teaspoon"},
  {"unsalted butter", "cup"},
  {"margarine", "cup"},
  {"vegetable oil", "cup"},
  {"olive oil", "cup"},
  {"shortening", "cup"},
  {"eggs", ""},
  {"egg whites", ""},
  {"egg yolks", ""},
  {"whole milk", "cup"},
  {"skim milk", "cup"},
  {"heavy cream", "cup"},
  {"half-and-half", "cup"},
  {"buttermilk", "cup"},
  {"sour cream", "cup"},
  {"yogurt", "cup"},
  {"vanilla extract", "teaspoon"},
  {"almond extract", "teaspoon"},
  {"lemon extract", "teaspoon"},
  {"orange extract", "teaspoon"},
  {"peppermint extract", "teaspoon"},
  {"cocoa powder", "cup"},
  {"unsweetened chocolate", "ml"},
  {"semisweet chocolate", "cup"},
  {"milk chocolate", "cup"},
  {"white chocolate", "cup"},
  {"chocolate chips", "cup"},
  {"dark chocolate", "ml"},
  {"baking chocolate", "ml"},
  {"mint", "cup"},
  {"cornstarch", "cup"},
  {"cornmeal", "cup"},
  {"almond flour", "cup"},
  {"coconut flour", "cup"},
  {"cake flour", "cup"},
  {"bread flour", "cup"},
  {"self-rising flour", "cup"},
  {"whole wheat flour", "cup"},
  {"rye flour", "cup"},
  {"oat flour", "cup"},
  {"rice flour", "cup"},
  {"gluten-free flour", "cup"},
  {"instant yeast", "teaspoons"},
  {"active dry yeast", "teaspoons"},
  {"fresh yeast", "ml"},
  {"honey", "cup"},
  {"maple syrup", "cup"},
  {"molasses", "cup"},
  {"agave nectar", "cup"},
  {"corn syrup", "cup"},
  {"brown rice syrup", "cup"},
  {"golden syrup", "cup"},
  {"coconut sugar", "cup"},
  {"palm sugar", "cup"},
  {"stevia", "cup"},
  {"splenda", "cup"},
  {"monk fruit sweetener", "cup"},
  {"applesauce", "cup"},
  {"mashed bananas", "cup"},
  {"pumpkin puree", "cup"},
  {"sweetened condensed milk", ""},
  {"evaporated milk", ""},
  {"dry milk powder", "cup"},
  {"cream cheese", "ml"},
  {"ricotta cheese", "cup"},
  {"mascarpone cheese", "cup"},
  {"lemon juice", "tablespoon"},
  {"lime juice", "tablespoon"},
  {"orange juice", "tablespoon"},
  {"lemon zest", ""},
  {"lime zest", ""},
  {"orange zest", ""},
  {"canned pumpkin", ""},
  {"canned sweet potato", ""},
  {"coconut milk", "cup"},
  {"coconut cream", "cup"},
  {"shredded coconut", "cup"},
  {"raisins", "cup"},
  {"dried cranberries", "cup"},
  {"dried cherries", "cup"},
  {"dried apricots", "cup"},
  {"chopped walnuts", "cup"},
  {"chopped pecans", "cup"},
  {"chopped almonds", "cup"},
  {"peanut butter", "cup"},
  {"almond butter", "cup"},
  {"ground cinnamon", "tablespoon"},
  {"ground nutmeg", "teaspoon"},
  {"ground cloves", "teaspoon"},
  {"ground ginger", "teaspoon"},
  {"pumpkin pie spice", "tablespoon"},
  {"apple pie spice", "tablespoon"},
  {"allspice", "tablespoon"},
  {"cardamom", "tablespoon"},
  {"anise seed", "tablespoon"},
  {"poppy seeds", "tablespoon"},
  {"sesame seeds", "tablespoon"},
  {"chia seeds", "tablespoon"},
  {"flax seeds", "tablespoon"},
  {"sunflower seeds", "cup"},
  {"hemp seeds", "tablespoon"},
  {"pepitas", "cup"},
  {"quinoa", "cup"},
  {"amaranth", "cup"},
  {"millet", "cup"},
  {"buckwheat", "cup"},
  {"barley", "cup"},
  {"spelt flour", "cup"},
  {"teff flour", "cup"},
  {"sorghum flour", "cup"},
  {"chickpea flour", "cup"},
  {"cassava flour", "cup"},
  {"arrowroot powder", "cup"},
  {"tapioca starch", "cup"},
  {"potato starch", "cup"},
  {"xanthan gum", "teaspoon"},
  {"sock extract", "teaspoon"},
  {"agar agar", "teaspoon"},
  {"gelatin", "tablespoon"},
  {"pectin", "tablespoon"},
  {"cream of tartar", "teaspoon"},
  {"citric acid", "teaspoon"},
  {"baking ammonia", "teaspoon"},
  {"sodium bicarbonate", "teaspoon"},
  {"calcium carbonate", "teaspoon"},
  {"monocalcium phosphate", "teaspoon"},
  {"sodium acid pyrophosphate", "teaspoon"},
  {"potassium bicarbonate", "teaspoon"},
  {"calcium propionate", "teaspoon"},
  {"ascorbic acid", "teaspoon"},
  {"acacia gum", "teaspoon"},
  {"arabic gum", "teaspoon"},
  {"carob gum", "teaspoon"},
  {"tragacanth gum", "teaspoon"},
  {"karaya gum", "teaspoon"},
  {"locust bean gum", "teaspoon"},
  {"guar gum", "teaspoon"},
  {"sodium alginate", "teaspoon"},
  {"potassium alginate", "teaspoon"},
  {"calcium alginate", "teaspoon"},
  {"magnesium alginate", "teaspoon"},
  {"sorbitol", "cup"},
  {"mannitol", "cup"},
  {"xylitol", "cup"},
  {"erythritol", "cup"},
  {"isomalt", "cup"},
  {"maltitol", "cup"},
  {"lactitol", "cup"},
  {"tagatose", "cup"},
  {"trehalose", "cup"},
  {"glucose syrup", "cup"},
  {"fructose", "cup"},
  {"dextrose", "cup"},
  {"lactose", "cup"},
  {"maltose", "cup"},
  {"invert sugar", "cup"},
  {"high fructose corn syrup", "cup"},
  {"date syrup", "cup"},
  {"fig syrup", "cup"},
  {"grape syrup", "cup"},
  {"pomegranate molasses", "cup"},
  {"tamarind paste", "cup"},
  {"rose water", "teaspoon"},
  {"orange blossom water", "teaspoon"},
  {"lavender extract", "teaspoon"},
  {"matcha powder", "tablespoon"},
  {"spirulina", "tablespoon"},
  {"chlorella", "tablespoon"},
  {"maca powder", "tablespoon"},
  {"lucuma powder", "tablespoon"},
  {"mesquite powder", "tablespoon"},
  {"baobab powder", "tablespoon"},
  {"acai powder", "tablespoon"},
  {"camu camu powder", "tablespoon"},
  {"bee pollen", "tablespoon"},
  {"royal jelly", "tablespoon"},
  {"propolis", "teaspoon"},
  {"wheat germ", "cup"},
  {"wheat bran", "cup"},
  {"oat bran", "cup"},
  {"rice bran", "cup"},
  {"psyllium husk", "tablespoon"},
  {"bamboo fiber", "tablespoon"},
  {"inulin", "tablespoon"},
  {"resistant starch", "tablespoon"},
  {"lupin flour", "cup"},
  {"fava bean flour", "cup"},
  {"soy flour", "cup"},
  {"peanut flour", "cup"},
  {"hazelnut flour", "cup"},
  {"pistachio flour", "cup"},
  {"macadamia flour", "cup"},
  {"brazil nut flour", "cup"},
  {"chestnut flour", "cup"},
  {"tiger nut flour", "cup"},
  {"water chestnut flour", "cup"},
  {"lotus root flour", "cup"},
  {"sacha inchi powder", "tablespoon"},
  {"hemp protein powder", "cup"},
  {"pea protein powder", "cup"},
  {"rice protein powder", "cup"},
  {"soy protein powder", "cup"},
  {"whey protein powder", "cup"},
  {"casein protein powder", "cup"},
  {"egg white protein powder", "cup"},
  {"collagen powder", "tablespoon"},
  {"gelatin powder", "tablespoon"},
  {"turmeric powder", "teaspoon"},
  {"ginger powder", "teaspoon"},
  {"garlic powder", "teaspoon"},
  {"onion powder", "teaspoon"},
  {"paprika", "teaspoon"},
  {"cayenne pepper", "teaspoon"},
  {"chili powder", "teaspoon"},
  {"smoked paprika", "teaspoon"},
  {"ground cumin", "teaspoon"},
  {"ground coriander", "teaspoon"},
  {"ground fennel", "teaspoon"},
  {"ground fenugreek", "teaspoon"},
  {"ground caraway", "teaspoon"},
  {"ground anise", "teaspoon"},
  {"ground star anise", "teaspoon"},
  {"ground mustard", "teaspoon"},
  {"ground bay leaf", "teaspoon"},
  {"ground curry powder", "tablespoon"},
  {"ground garam masala", "tablespoon"},
  {"ground tandoori masala", "tablespoon"},
  {"ground za'atar", "tablespoon"},
  {"ground sumac", "teaspoon"},
  {"ground harissa", "teaspoon"},
  {"ground berbere", "teaspoon"},
  {"ground ras el hanout", "teaspoon"},
  {"ground baharat", "teaspoon"},
  {"ground chinese five-spice", "teaspoon"},
  {"ground herbes de provence", "teaspoon"},
  {"ground italian seasoning", "teaspoon"},
  {"ground poultry seasoning", "teaspoon"},
  {"ground taco seasoning", "teaspoon"},
  {"ground chili seasoning", "teaspoon"},
  {"ground cajun seasoning", "teaspoon"},
  {"ground creole seasoning", "teaspoon"},
  {"ground jerk seasoning", "teaspoon"},
  {"ground adobo seasoning", "teaspoon"},
  {"ground bbq seasoning", "teaspoon"},
  {"ground ranch seasoning", "teaspoon"},
  {"ground everything bagel seasoning", "teaspoon"},
  {"ground furikake", "teaspoon"},
  {"ground togarashi", "teaspoon"},
  {"ground dukkah", "teaspoon"},
  {"ground schichimi togarashi", "teaspoon"}
};

#endif // OBFUSCATE_H
