#ifndef OBFUSCATE_H
#define OBFUSCATE_H

struct Ingredient {
  char *name;
  char *measure;
  char c;
};

struct Ingredient ings[] = {
  {"active dry yeast", "teaspoons "},
  {"heavy cream", "cups "},
  {"dark chocolate", "cups "},
  {"sweet potatoes", ""},
  {"pumpkins", ""},
  {"half-and-half", "cups "},
  {"sour cream", "cups "},
  {"peppermint extract", "teaspoons "},
  {"dried apricots", "cups "},
  {"olive oil", "cups "},
  {"baking chocolate", "cups "},
  {"bread flour", "cups "},
  {"unsalted butter", "cups "},
  {"brown sugar", "cups "},
  {"salt", "teaspoons "},
  {"golden syrup", "cups "},
  {"egg whites", ""},
  {"dried cranberries", "cups "},
  {"cake flour", "cups "},
  {"rye flour", "cups "},
  {"rice flour", "cups "},
  {"ground cinnamon", "tablespoons "},
  {"chopped nuts ", "cups "},
  {"orange extract", "teaspoons "},
  {"maple syrup", "cups "},
  {"granulated sugar", "cups "},
  {"limes' zests", ""},
  {"nut butters ", "cups "},
  {"whole wheat flour", "cups "},
  {"stevia", "cups "},
  {"white chocolate", "cups "},
  {"coconut cream", "cups "},
  {"skim milk", "cups "},
  {"allspice", "tablespoons "},
  {"agave nectar", "cups "},
  {"sweetened condensed milk ", "cans "},
  {"yogurt", "cups "},
  {"margarine", "cups "},
  {"molasses", "cups "},
  {"cream cheese", "cups "},
  {"self-rising flour", "cups "},
  {"dry milk powder", "cups "},
  {"corn syrup", "cups "},
  {"dried cherries", "cups "},
  {"unsweetened chocolate", "cups "},
  {"buttermilk", "cups "},
  {"chocolate chips", "cups "},
  {"gluten-free flour", "cups "},
  {"applesauce", "cups "},
  {"vanilla extract", "teaspoons "},
  {"all-purpose flour", "cups "},
  {"palm sugar", "cups "},
  {"lemon juice", "tablespoons "},
  {"milk chocolate", "cups "},
  {"oat flour", "cups "},
  {"almond extract", "teaspoons "},
  {"ground nutmeg", "teaspoons "},
  {"evaporated milk ", "cans "},
  {"ricotta cheese", "cups "},
  {"mashed bananas", "cups "},
  {"cardamom", "tablespoons "},
  {"lemons' zests", ""},
  {"semisweet chocolate", "cups "},
  {"sesame seeds", "tablespoons "},
  {"powdered sugar", "cups "},
  {"almond flour", "cups "},
  {"lime juice", "tablespoons "},
  {"monk fruit sweetener", "cups "},
  {"whole milk", "cups "},
  {"ground ginger", "teaspoons "},
  {"lemon extract", "teaspoons "},
  {"poppy seeds", "tablespoons "},
  {"baking powder", "tablespoons "},
  {"shortening", "cups "},
  {"orange juice", "tablespoons "},
  {"egg yolks", ""},
  {"coconut flour", "cups "},
  {"raisins", "cups "},
  {"apple pie spice", "tablespoons "},
  {"mascarpone cheese", "cups "},
  {"pumpkin pie spice", "tablespoons "},
  {"cornmeal", "cups "},
  {"honey", "cups "},
  {"cocoa powder", "cups "},
  {"anise seed", "tablespoons "},
  {"coconut sugar", "cups "},
  {"baking soda", "teaspoons "},
  {"ground cloves", "teaspoons "},
  {"splenda", "cups "},
  {"brown rice syrup", "cups "},
  {"pumpkin puree", "cups "},
  {"coconut milk", "cups "},
  {"instant yeast", "teaspoons "},
  {"chia seeds", "tablespoons "},
  {"cornstarch", "cups "},
  {"oranges' zests", ""},
  {"large eggs", ""},
  {"vegetable oil", "cups "},
  {"shredded coconut", "cups "},
  {"fresh yeast", "cup"}
};

#endif // OBFUSCATE_H
